"""
Interactive configurator for managing API keys, providers, and settings.
"""

import subprocess
from pathlib import Path


try:
    from InquirerPy import inquirer
    from InquirerPy.base.control import Choice
    from InquirerPy.separator import Separator

    HAS_INQUIRERPY = True
except ImportError:
    HAS_INQUIRERPY = False


class NinjaConfigurator:
    """Interactive configurator for ninja-mcp."""

    def __init__(self):
        self.config_file = Path.home() / ".ninja-mcp.env"
        self.config = self._load_config()

    def _load_config(self) -> dict[str, str]:
        """Load configuration from file."""
        config = {}
        if self.config_file.exists():
            with open(self.config_file) as f:
                for line in f:
                    config_line = line.strip()
                    if config_line and not config_line.startswith("#") and "=" in config_line:
                        key, value = config_line.split("=", 1)
                        config[key.strip()] = value.strip()
        return config

    def _save_config(self) -> None:
        """Save configuration to file."""
        self.config_file.parent.mkdir(parents=True, exist_ok=True)
        with open(self.config_file, "w") as f:
            f.write("# Ninja MCP Configuration\n")
            f.write("# Generated by ninja-config\n\n")
            for key, value in sorted(self.config.items()):
                f.write(f"{key}={value}\n")
        print(f"\n✓ Configuration saved to {self.config_file}")

    def _get_masked_value(self, value: str) -> str:
        """Return masked version of API key."""
        if not value or len(value) < 8:
            return "not set"
        return f"{value[:4]}...{value[-4:]}"

    def run(self) -> None:
        """Run the main configurator loop."""
        if not HAS_INQUIRERPY:
            print("⚠️  InquirerPy not installed for interactive menus")
            print("   Using basic configuration mode")
            self._basic_config()
            return

        while True:
            action = self._show_main_menu()
            if not action:
                break

            if action == "api_keys":
                self._configure_api_keys()
            elif action == "operators":
                self._configure_operators()
            elif action == "providers":
                self._configure_providers()
            elif action == "search":
                self._configure_search()
            elif action == "delete_component":
                self._delete_component()
            elif action == "show":
                self._show_config()
            elif action == "reset":
                self._reset_config()

    def _show_main_menu(self) -> str | None:
        """Show main configuration menu."""
        print("\n" + "=" * 70)
        print("  ⚙️  NINJA CONFIGURATION MANAGER")
        print("=" * 70 + "\n")

        choices = [
            Choice(
                value="api_keys",
                name="🔑 Manage API Keys  •  Add/update OpenRouter, Perplexity, etc",
            ),
            Choice(
                value="operators", name="🎯 Configure Operators  •  Set up Aider, OpenCode, Gemini"
            ),
            Choice(
                value="providers", name="🌐 Manage Providers  •  Authenticate OpenCode providers"
            ),
            Choice(value="search", name="🔍 Search Settings  •  Configure research provider"),
            Separator(),
            Choice(value="delete_component", name="🗑️  Delete Component  •  Remove module configuration"),
            Choice(value="show", name="📋 Show Configuration  •  View current settings"),
            Choice(value="reset", name="🗑️  Reset All  •  Clear all settings"),
            Separator(),
            Choice(value="exit", name="Exit"),
        ]

        result = inquirer.select(
            message="What would you like to configure?",
            choices=choices,
            pointer="►",
        ).execute()

        return None if result == "exit" else result

    def _configure_api_keys(self) -> None:
        """Configure API keys interactively."""
        print("\n" + "=" * 70)
        print("  🔑 API KEY CONFIGURATION")
        print("=" * 70 + "\n")

        keys = [
            (
                "OPENROUTER_API_KEY",
                "OpenRouter",
                "https://openrouter.ai/keys",
                "For Aider - OpenRouter API key",
            ),
            (
                "PERPLEXITY_API_KEY",
                "Perplexity AI",
                "https://www.perplexity.ai/settings/api",
                "For researcher - best research quality",
            ),
            (
                "SERPER_API_KEY",
                "Serper/Google",
                "https://serper.dev",
                "For researcher - Google search API",
            ),
            (
                "GEMINI_API_KEY",
                "Google Gemini",
                "https://makersuite.google.com/app/apikey",
                "For Gemini CLI operator",
            ),
        ]

        # Show current status
        print("Current API keys:\n")
        for key, name, _, _ in keys:
            current = self.config.get(key, "")
            status = self._get_masked_value(current)
            print(f"  {name:20} {status}")
        print()

        # Select which key to configure
        choices = [
            Choice(
                value=key,
                name=f"{name:20} • {desc}  [{self._get_masked_value(self.config.get(key, ''))}]",
            )
            for key, name, _, desc in keys
        ]
        choices.append(Separator())
        choices.append(Choice(value=None, name="← Back"))

        selected_key = inquirer.select(
            message="Select API key to configure:",
            choices=choices,
            pointer="►",
        ).execute()

        if not selected_key:
            return

        # Find key info
        key_info = next((k for k in keys if k[0] == selected_key), None)
        if not key_info:
            return

        key_name, display_name, url, desc = key_info

        print(f"\n{display_name} API Key")
        print(f"Get your key from: {url}\n")

        current = self.config.get(key_name, "")
        if current:
            print(f"Current value: {self._get_masked_value(current)}")

        # Get new value
        new_value = inquirer.secret(
            message=f"Enter new {display_name} API key (or leave empty to keep current):",
        ).execute()

        if new_value:
            self.config[key_name] = new_value
            self._save_config()
            print(f"✓ {display_name} API key updated")
        else:
            print("✓ No changes made")

    def _configure_operators(self) -> None:
        """Configure operator settings with provider-first flow."""
        print("\n" + "=" * 70)
        print("  🎯 OPERATOR CONFIGURATION")
        print("=" * 70 + "\n")

        # Check installed operators
        operators = []
        if subprocess.run(["which", "opencode"], capture_output=True, check=False).returncode == 0:
            operators.append(
                (
                    "opencode",
                    "OpenCode",
                    "Multi-provider CLI (75+ LLMs)",
                    ["anthropic", "google", "openai", "github", "zai"],
                )
            )
        if subprocess.run(["which", "aider"], capture_output=True, check=False).returncode == 0:
            operators.append(("aider", "Aider", "OpenRouter-based CLI", ["openrouter"]))
        if subprocess.run(["which", "gemini"], capture_output=True, check=False).returncode == 0:
            operators.append(("gemini", "Gemini CLI", "Google Gemini native CLI", ["google"]))
        if subprocess.run(["which", "claude"], capture_output=True, check=False).returncode == 0:
            operators.append(("claude", "Claude Code", "Anthropic's official CLI", ["anthropic"]))

        if not operators:
            print("✗ No operators found!")
            print("\nInstall at least one operator:")
            print("  • OpenCode: https://opencode.dev")
            print("  • Aider: uv tool install aider-chat")
            print("  • Claude Code: https://claude.ai/download")
            print("  • Gemini: npm install -g @google/generative-ai-cli")
            return

        # Show current operator
        current_bin = self.config.get("NINJA_CODE_BIN", "aider")
        current_model = self.config.get("NINJA_MODEL", "")
        print(f"Current operator: {current_bin}")
        if current_model:
            print(f"Current model: {current_model}")
        print()

        # Select operator with provider info
        choices = []
        for cmd, name, desc, providers in operators:
            provider_str = ", ".join(providers)
            choices.append(
                Choice(value=cmd, name=f"{name:15} • {desc}  [Providers: {provider_str}]")
            )
        choices.append(Separator())
        choices.append(Choice(value=None, name="← Back"))

        selected = inquirer.select(
            message="Select operator:",
            choices=choices,
            pointer="►",
        ).execute()

        if selected:
            self.config["NINJA_CODE_BIN"] = selected
            # Clear model selection when changing operator
            if "NINJA_MODEL" in self.config:
                del self.config["NINJA_MODEL"]
            self._save_config()
            print(f"\n✓ Operator set to: {selected}")

            # Show available providers for selected operator
            selected_operator = next((op for op in operators if op[0] == selected), None)
            if selected_operator:
                _, name, _, providers = selected_operator
                print(f"\n📋 Available providers for {name}:")
                for provider in providers:
                    print(f"   • {provider}")

            # Prompt for authentication if needed
            if selected == "opencode":
                print("\n💡 Run 'ninja-config configure' → 'Manage Providers' to authenticate")
            elif selected == "claude":
                print("\n💡 Run 'claude auth' to authenticate with Anthropic")
            elif selected == "aider":
                print("\n💡 Set OPENROUTER_API_KEY in 'API Keys' menu")

    def _configure_providers(self) -> None:
        """Configure OpenCode authentication with z.ai support."""
        print("\n" + "=" * 70)
        print("  🌐 PROVIDER AUTHENTICATION (OpenCode)")
        print("=" * 70 + "\n")

        if subprocess.run(["which", "opencode"], capture_output=True, check=False).returncode != 0:
            print("✗ OpenCode not installed")
            print("  Install from: https://opencode.dev")
            return

        providers = [
            ("anthropic", "Anthropic/Claude", "opencode auth anthropic"),
            ("google", "Google/Gemini", "opencode auth google"),
            ("openai", "OpenAI/GPT", "opencode auth openai"),
            ("github", "GitHub Copilot", "opencode auth github"),
            ("zai", "Z.ai / Zhipu AI", "opencode auth zai"),
        ]

        # Check current auth status
        print("Checking authentication status...\n")
        result = subprocess.run(
            ["opencode", "auth", "list"], capture_output=True, text=True, check=False
        )
        authenticated = []
        for provider, _, _ in providers:
            if provider in result.stdout.lower() or (
                provider == "zai" and "zhipu" in result.stdout.lower()
            ):
                authenticated.append(provider)
                print(f"  ✓ {provider}")
            else:
                print(f"  ✗ {provider}")
        print()

        # Select provider to authenticate
        choices = [
            Choice(
                value=cmd,
                name=f"{name:25} • {'✓ Authenticated' if provider in authenticated else '✗ Not authenticated'}",
            )
            for provider, name, cmd in providers
        ]
        choices.append(Separator())
        choices.append(Choice(value=None, name="← Back"))

        selected = inquirer.select(
            message="Select provider to authenticate:",
            choices=choices,
            pointer="►",
        ).execute()

        if selected:
            print(f"\n🔄 Running: {selected}")
            print("   Follow the prompts to authenticate...\n")
            subprocess.run(selected.split(), check=False)
            print("\n✓ Authentication complete")

    def _configure_search(self) -> None:
        """Configure search provider for ninja-researcher with Perplexity model selection."""
        print("\n" + "=" * 70)
        print("  🔍 SEARCH PROVIDER CONFIGURATION")
        print("=" * 70 + "\n")

        current = self.config.get("NINJA_SEARCH_PROVIDER", "duckduckgo")
        current_model = self.config.get("NINJA_RESEARCHER_MODEL", "sonar")
        print(f"Current provider: {current}")
        if current == "perplexity":
            print(f"Current model: {current_model}")
        print()

        choices = [
            Choice(value="duckduckgo", name="DuckDuckGo  •  Free, no API key needed"),
            Choice(value="perplexity", name="Perplexity AI  •  Best quality, needs API key"),
            Choice(value="serper", name="Serper/Google  •  Good quality, needs API key"),
        ]

        selected = inquirer.select(
            message="Select search provider:",
            choices=choices,
            pointer="►",
            default=current,
        ).execute()

        if selected:
            self.config["NINJA_SEARCH_PROVIDER"] = selected
            self._save_config()
            print(f"\n✓ Search provider set to: {selected}")

            # Check if API key needed
            if selected == "perplexity":
                if not self.config.get("PERPLEXITY_API_KEY"):
                    print("\n⚠️  Perplexity API key required")
                    print("   Go to 'Manage API Keys' to add it")
                else:
                    # Offer Perplexity model selection
                    self._configure_perplexity_model()
            elif selected == "serper" and not self.config.get("SERPER_API_KEY"):
                print("\n⚠️  Serper API key required")
                print("   Go to 'Manage API Keys' to add it")

    def _configure_perplexity_model(self) -> None:
        """Configure Perplexity model for researcher."""
        print("\n" + "-" * 50)
        print("  📊 PERPLEXITY MODEL SELECTION")
        print("-" * 50 + "\n")

        # Perplexity models
        perplexity_models = [
            ("sonar", "Sonar", "Fast search-focused model"),
            ("sonar-pro", "Sonar Pro", "Advanced search with better reasoning"),
            ("sonar-reasoning", "Sonar Reasoning", "Complex reasoning with search"),
        ]

        current_model = self.config.get("NINJA_RESEARCHER_MODEL", "sonar")
        print(f"Current model: {current_model}\n")

        choices = [
            Choice(value=model_id, name=f"{name:20} • {desc}")
            for model_id, name, desc in perplexity_models
        ]
        choices.append(Separator())
        choices.append(Choice(value=None, name="← Keep current"))

        selected = inquirer.select(
            message="Select Perplexity model:",
            choices=choices,
            pointer="►",
            default=current_model,
        ).execute()

        if selected:
            self.config["NINJA_RESEARCHER_MODEL"] = selected
            self._save_config()
            print(f"\n✓ Researcher model set to: {selected}")

    def _delete_component(self) -> None:
        """Delete a component's configuration."""
        from ninja_config.model_selector import delete_component, get_active_modules

        print("\n" + "=" * 70)
        print("  🗑️  DELETE COMPONENT CONFIGURATION")
        print("=" * 70 + "\n")

        # Get all known components
        all_components = [
            "ninja-coder",
            "ninja-researcher",
            "ninja-secretary",
            "ninja-resources",
            "ninja-prompts",
        ]
        active_modules = get_active_modules()

        # Show which are active
        print("Available components:\n")
        choices = []
        for component in all_components:
            status = "✓ Active" if component in active_modules else "✗ Not installed"
            choices.append(Choice(value=component, name=f"{component:20} • {status}"))

        choices.append(Separator())
        choices.append(Choice(value=None, name="← Back"))

        selected = inquirer.select(
            message="Select component to delete configuration:",
            choices=choices,
            pointer="►",
        ).execute()

        if not selected:
            return

        # Confirm deletion
        confirm = inquirer.confirm(
            message=f"⚠️  Delete all configuration for {selected}?",
            default=False,
        ).execute()

        if confirm:
            if delete_component(selected):
                print(f"\n✓ Configuration for {selected} deleted successfully")
            else:
                print(f"\n✗ Failed to delete configuration for {selected}")
        else:
            print("\n✓ Cancelled")

    def _show_config(self) -> None:
        """Show current configuration."""
        print("\n" + "=" * 70)
        print("  📋 CURRENT CONFIGURATION")
        print("=" * 70 + "\n")

        if not self.config:
            print("No configuration found")
            return

        # Group by category
        api_keys = {k: v for k, v in self.config.items() if "API_KEY" in k}
        operators = {
            k: v for k, v in self.config.items() if k.startswith("NINJA_CODE") or k == "NINJA_MODEL"
        }
        search = {k: v for k, v in self.config.items() if "SEARCH" in k}
        other = {
            k: v
            for k, v in self.config.items()
            if k not in api_keys and k not in operators and k not in search
        }

        if api_keys:
            print("🔑 API Keys:")
            for key, value in sorted(api_keys.items()):
                print(f"  {key:25} {self._get_masked_value(value)}")
            print()

        if operators:
            print("🎯 Operator:")
            for key, value in sorted(operators.items()):
                print(f"  {key:25} {value}")
            print()

        if search:
            print("🔍 Search:")
            for key, value in sorted(search.items()):
                print(f"  {key:25} {value}")
            print()

        if other:
            print("⚙️  Other:")
            for key, value in sorted(other.items()):
                print(f"  {key:25} {value}")
            print()

        print(f"Configuration file: {self.config_file}")

    def _reset_config(self) -> None:
        """Reset configuration."""
        if not HAS_INQUIRERPY:
            response = (
                input("\n⚠️  This will delete all configuration. Continue? [y/N]: ").strip().lower()
            )
            confirm = response == "y"
        else:
            confirm = inquirer.confirm(
                message="⚠️  This will delete all configuration. Continue?",
                default=False,
            ).execute()

        if confirm:
            self.config = {}
            if self.config_file.exists():
                self.config_file.unlink()
            print("\n✓ Configuration reset")
        else:
            print("\n✓ Cancelled")

    def _basic_config(self) -> None:
        """Basic configuration without InquirerPy."""
        print("\nBasic Configuration Mode\n")
        print("1) Configure API keys")
        print("2) Show configuration")
        print("3) Exit")

        choice = input("\nSelect [1]: ").strip() or "1"

        if choice == "1":
            print("\nOpenRouter API Key (for Aider):")
            key = input("Enter key (or press Enter to skip): ").strip()
            if key:
                self.config["OPENROUTER_API_KEY"] = key
                self._save_config()
        elif choice == "2":
            self._show_config()


def run_configurator() -> int:
    """Run the interactive configurator."""
    configurator = NinjaConfigurator()
    try:
        configurator.run()
        return 0
    except KeyboardInterrupt:
        print("\n\n✗ Cancelled")
        return 1


if __name__ == "__main__":
    import sys

    sys.exit(run_configurator())
